spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  #这个mybatis的文件夹在resource下面，以及专门的文件：mybatis.cfg.xml
  type-aliases-package: org.xwl.entity # 所有Entity别名类所在包
  #用于类表映射
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml # mapper映射文件

spring:
  profiles: dev
  application:
    name: microservicecloud-dept #对外暴露的微服务名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://26.32.0.50:3306/cloudDB01?useSSL=true&serverTimezone=UTC # 数据库名称
    username: root
    password: 200826
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初始化连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 200 # 等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001 # 原来显示：UP (1) - DESKTOP-DM7RH5I:microservicecloud-dept:8001
    prefer-ip-address: true     #访问路径可以显示IP地址
info:
  app.name: microservicecloud-dept
  company.name: www.xwl.org
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml # mybatis配置文件所在路径
  #这个mybatis的文件夹在resource下面，以及专门的文件：mybatis.cfg.xml
  type-aliases-package: org.xwl.entity # 所有Entity别名类所在包
  #用于类表映射
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml # mapper映射文件

spring:
  profiles: test
  application:
    name: microservicecloud-dept #对外暴露的微服务名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动包
    url: jdbc:mysql://26.32.0.50:3306/cloudDB02?useSSL=true&serverTimezone=UTC # 数据库名称
    username: root
    password: 200826
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5 # 初始化连接数
      max-total: 5 # 最大连接数
      max-wait-millis: 200 # 等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001 # 原来显示：UP (1) - DESKTOP-DM7RH5I:microservicecloud-dept:8001
    prefer-ip-address: true     #访问路径可以显示IP地址
info:
  app.name: microservicecloud-dept
  company.name: www.xwl.org
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}




